const avatarList = [
  { value: '그루스' },
  { value: '나유' },
  { value: '라임' },
  { value: '러스크' },
  { value: '루나릿트' },
  { value: '리어앨리스' },
  { value: '리파' },
  { value: '린도' },
  { value: '마누카' },
  { value: '마리엘' },
  { value: '마메 히나타' },
  { value: '마야' },
  { value: '마키' },
  { value: '마후유' },
  { value: '메리노' },
  { value: '메이윤' },
  { value: '모에' },
  { value: '모피라' },
  { value: '미나 호시' },
  { value: '미나세' },
  { value: '미쉐' },
  { value: '미즈키' },
  { value: '민트' },
  { value: '밀크' },
  { value: '베일' },
  { value: '사네코' },
  { value: '사타리나' },
  { value: '셀레스티아' },
  { value: '스즈하나' },
  { value: '시리우스' },
  { value: '시오' },
  { value: '시폰' },
  { value: '신라' },
  { value: '씨엘' },
  { value: '안리' },
  { value: '우사사키' },
  { value: '우콘' },
  { value: '울페리아' },
  { value: '유우코' },
  { value: '이메리스' },
  { value: '이요' },
  { value: '카린' },
  { value: '코마노' },
  { value: '코유키' },
  { value: '코코아' },
  { value: '쿄코' },
  { value: '쿠로나츠' },
  { value: '키쿄' },
  { value: '티엔' },
  { value: '하카' },
  { value: '기타' },
];

export default avatarList;

// avatarList.sort((a, b) => a.value.localeCompare(b.value));
